### PR TITLE
Allow proxying to HTTPS servers.

### PR DESCRIPTION
**Pull request by benjamin-wagon**
This PR does not implement HTTPS requests when using `rawProxyTo`. Is this possible?

### CODE REVIEW

**Comment by gregwebs** [comment]
Also wondering if it is a bad idea to use `http-proxy` instead of `http-reverse-proxy` because it supports SSL?

**Comment by snoyberg** [comment]
I'd rather do this in a way that doesn't break backwards compatibility with all users. How about adding a new constructors WPRProxyDestSecure instead?

**Comment by benjamin-wagon** [comment]
That sounds super reasonable; solves the rawProxyTo issue as well!

I'll submit a follow-up commit tomorrow.

**Comment by benjamin-wagon** [comment]
Having both `WPRProxyDestSecure` and `WPRModifiedRequestSecure` feels a tiny bit icky, but I'm not seeing a better approach.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
