### PR TITLE
Update `wpsProcessBody` to accept response's initial request

### LINKED ISSUE #24: Be able to process a response's body based on its request.
Greetings,

I have a need where I got to modify a response only when its request meets some requirements. I'm keen to submit a PR, the change looks trivial. `WaiProxySettings` 's `wpsProcessBody` record field seems to be the right place. 

However, that patch will introduce a breaking change. Would you agree to accept such patch?

Regards.

### PR DESCRIPTION
**Pull request by YoEight**
Fix #24

### CODE REVIEW

**Comment by phaazon** [comment]
> All your requests are belong to us!

**Comment by YoEight** [comment]
All errors reported by CI happened during dependency build time.

**Comment by snoyberg** [comment]
I'm OK with this breaking change. Can you bump the major version in the cabal file, add a note to the ChangeLog, and add a note on which version the change in API occurred on in the exposed identifier itself?

**Comment by YoEight** [comment]
@snoyberg 
Sure but what did you mean by:
> and add a note on which version the change in API occurred on in the exposed identifier itself

?

**Comment by snoyberg** [comment]
Sure, I meant a note like:

> The API for this function changed to include the extra parameter in version X.Y.Z

**Comment by YoEight** [comment]
@snoyberg  
Done, thanks for the quick reply.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
