### PR TITLE
Add Eq instance for ProxyDest

### PR DESCRIPTION
**Pull request by arianvp**
I needed this at work where we keep a map of proxy destiniations

### CODE REVIEW

**Comment by snoyberg** [comment]
No objection. But as long we we're doing this, what about adding other typeclasses like `Show`, `Read`, and `Ord`? Also, can you include a minor version bump and a comment in the ChangeLog?

**Comment by arianvp** [comment]
Do we also want `Data,Typeable,Generic,Hashable` etc?

**Comment by snoyberg** [comment]
@arianvp If it doesn't add new dependencies and isn't stupid, I'd go for it. All of those make sense to me.

**Comment by arianvp** [comment]
I'm not sure why the build failed

**Comment by snoyberg** [comment]
Travis network failure, pay it no mind. If you're going to update with the additional instances, I'll hold off merging. If you want it merged as-is, it's good to go.

**Comment by arianvp** [comment]
Alright, I'll add the other instances as well, and then we can merge

**Comment by arianvp** [comment]
@snoyberg done!

**Comment by snoyberg** [comment]
Awesome, just waiting for Travis. Since I'm going to go offline soon, I may only hit merge next week, but LGTM. Thanks!

**Comment by snoyberg** [comment]
Awesome, just waiting for Travis. Since I'm going to go offline soon, I may only hit merge next week, but LGTM. Thanks!

**Pull request merged**
